version: '3.7'
services:
  payment:
    container_name: payment
    build:
      context: ./payment
      args:
        - APP_ENV=development
        - COMPOSER_NO_INTERACTION=0
    image: payment
    ports:
      - 3006:80
    volumes:
      - ./payment/src:/app
    command: bash -c "composer update --lock --prefer-source && supervisord"
  mysql-server:
    image: mysql:5.7
    container_name: payment-db
    environment:
      MYSQL_DATABASE: payment-db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./payment-db/data:/var/lib/mysql:rw