version: '3.7'
services:
  mysql-server:
    image: mysql:5.7
    container_name: payment-db
    environment:
      MYSQL_DATABASE: payment-db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3307:3306
    volumes:
    - ./data:/var/lib/mysql:rw